name: Build Android APK

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build web app
        run: npm run build

      - name: Install global Capacitor & Ionic
        run: npm install -g @ionic/cli @capacitor/cli

      - name: Build web app
        run: npm run build

      - name: Add Android platform
        run: npx cap add android

      - name: Copy web assets
        run: npx cap copy android

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Talkio-android
          path: android/app/build/outputs/apk/debug/*.apk